version: "3.8"

services:
  app:
    image: "molel/cloud-drive:${DOCKER_IMAGE_VERSION}"
    container_name: app
    restart: on-failure
    ports:
      - "${APP_PORT}:8080"
    volumes:
      - "${LOGS_FOLDER}:/app/logs"
    depends_on:
      - postgres
      - mongodb

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - "${DATABASES_FOLDER}/postgres:/var/lib/postgresql/data"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - "${DATABASES_FOLDER}/mongodb:/data/db"
